# Default values for datapusher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tnristwdb/datapusher-plus
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

datapusher:
  # datapusher.maxContentLength -- Maximum size of content to be uploaded in bytes.
  maxContentLength: "10485760"
  # datapusher.chunkSize -- Size of chunks of the data that is being downloaded in bytes
  chunkSize: "16384"
  # datapusher.insertRows -- Number of rows to take from the data and upload them as chunks to datastore
  insertRows: "250"
  # datapusher.downloadTimeout -- Timeout limit of the download request
  downloadTimeout: "30"
  # datapusher.datapusherSslVerify -- Enable or disable (boolean) verification of SSL when trying to get resources. Default: True
  datapusherSslVerify: "0"
  # datapusher.datapusherRewriteResources -- Enable or disable (boolean) whether datapusher should rewrite resources uploaded to CKAN's filestore, since datapusher takes the CKAN Site URL value for generating the resource URL. Default: False
  datapusherRewriteResources: "True"
  # Sets the rewrite URL that datapushed will rewrite resources that are uploaded to CKAN's filestore. Default: http://ckan:5000
  datapusherRewriteUrl: http://ckan
  # qsv related parameters
  qsv:
    deduplicate: "1"
    bin: "/usr/local/bin/qsvdp"
  # jobs db info
  jobs:
    user: "jobsUserHere"
    password: "jobsPasswordHere"
    dbName: "jobsDbNameHere"
  # datastore db info
  datastore:
    user: "datastoreUserHere"
    password: "datastorePasswordHere"
    dbName: "datastoreDbNameHere"
  # location for datastore logfile
  logFile: "/tmp/ckan_service.log"
  # stdErr enabled or not (0 for False or 1 for True)
  stdErr: "1"
  # default number of rows to display
  previewRows: "1000"
  # default display excel sheet enabled or not (0 for False or 1 for True)
  defaultExcelSheet: "0"
  # auto aliasing of columns enabled or not (0 for False or 1 for True)
  autoAlias: "1"
  # datapusher write engine url
  writeEngineUrl: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8800

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}