############################
### Build CKAN container ###
############################

FROM ckan/ckan as ckan-plugins

### TODO: download ckan plugins via scripts from ./plugins
### TODO: store plugins in dedicated directory

FROM ckan/ckan as ckan-patches

### TODO: download ckan patches from ./patches
### TODO: store patches in dedicated directory

FROM ckan/ckan as ckan-build

### TODO: install ckan and apply plugins and patches
### TODO: pull ckan env vars using ckan extension

### TODO: apply ckan ini to ckan install using ckan cli

### TODO: start ckan

### TODO: ckan init scripts here

### TODO: health check



