version: "3"

volumes:
  pg_data:

services:
  datapusher:
    depends_on:
      db:
        condition: service_healthy
    container_name: datapusher-plus
    build:
      context: ./1-datapusher-plus/0.15.0/
      dockerfile: Dockerfile
    image: datapusher-plus:0.15.0
    networks:
      - frontend
      - backend
    ports:
      - "8800:8800"
    env_file:
      - ./.env
  db:
    container_name: db-datapusher-plus
    build:
      context: ./2-postgresql/
      dockerfile: Dockerfile
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=the_password
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./2-postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "jobs"]
      interval: 10s
      timeout: 10s
      retries: 5
networks:
  frontend:
  backend: