#!/bin/bash
set -e

echo ${DATASTORE_DB_USER} ${DATASTORE_DB_PASSWORD}
echo ${DATASTORE_DB_NAME} ${DATASTORE_DB_USER}
echo ${JOBS_DB_USER} ${JOBS_DB_PASSWORD}
echo ${JOBS_DB_NAME} ${JOBS_DB_USER}
echo ${DATASTORE_DB_NAME} TO ${DATASTORE_DB_USER}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE ${DATASTORE_DB_USER} LOGIN PASSWORD '${DATASTORE_DB_PASSWORD}';
    CREATE DATABASE ${DATASTORE_DB_NAME} OWNER ${DATASTORE_DB_USER} ENCODING 'utf-8';
    CREATE ROLE ${JOBS_DB_USER} LOGIN PASSWORD '${JOBS_DB_PASSWORD}';
    CREATE DATABASE ${JOBS_DB_NAME} OWNER ${JOBS_DB_USER} ENCODING 'utf-8';
    GRANT CREATE, CONNECT, TEMPORARY ON DATABASE ${DATASTORE_DB_NAME} TO ${DATASTORE_DB_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO ${DATASTORE_DB_USER};
EOSQL