# pings database and retries until service up
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-datapusher-init
spec:
  template:
    spec:
      volumes:
        - name: {{ .Release.Name }}-datapusher-init-volume
          configMap:
            name: {{ .Release.Name }}-datapusher-init-configmap
        - name: {{ .Release.Name }}-datapusher-configset-volume
          configMap:
            name: {{ .Release.Name }}-datapusher-configset-configmap
      containers:
      - name: {{ .Release.Name }}-datapusher-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DB_HOST
          value: {{ .Values.DBHost }}
        # Master DB creds
        - name: POSTGRES_USER
          value: {{ .Values.datapusher.masterDBUser }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.datapusher.masterDBPassword }}
        - name: POSTGRES_DB
          value: {{ .Values.datapusher.masterDBName }}
        # Datapusher jobs DB creds
        - name: DATAPUSHER_JOBS_DB_USER
          value: {{ .Values.datapusher.datapusherJobsDBUser }}
        - name: DATAPUSHER_JOBS_DB_PASSWORD
          value: {{ .Values.datapusher.datapusherJobsDBPassword }}
        - name: DATAPUSHER_JOBS_DB_NAME
          value: {{ .Values.datapusher.datapusherJobsDBName }}
        command: ["/usr/lib/ckan/datapusher-plus/bin/python"]
        args: ["/srv/datapusher-init/datapusher-init.py"]
        volumeMounts:
        - name: {{ .Release.Name }}-datapusher-init-volume
          mountPath: /srv/datapusher-init
        - name: {{ .Release.Name }}-datapusher-configset-volume
          mountPath: /srv/datapusher-configset
      restartPolicy: Never
  backoffLimit: 3