# pings database and retries until service up
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-datapusher-init
spec:
  template:
    spec:
      volumes:
        - name: {{ .Release.Name }}-datapusher-init-volume
          configMap:
            name: {{ .Release.Name }}-datapusher-init-configmap
        - name: {{ .Release.Name }}-datapusher-configset-volume
          configMap:
            name: {{ .Release.Name }}-datapusher-configset-configmap
      containers:
      - name: {{ .Release.Name }}-datapusher-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TEST
          value: "TEST ENVIRONMENT VARIABLE"
        command: ["/usr/lib/ckan/datapusher-plus/bin/python"]
        args: ["/srv/datapusher-init/datapusher-init.py"]
        volumeMounts:
        - name: {{ .Release.Name }}-datapusher-init-volume
          mountPath: /srv/datapusher-init
        - name: {{ .Release.Name }}-datapusher-configset-volume
          mountPath: /srv/datapusher-configset
      restartPolicy: Never
  backoffLimit: 3